name: 'Image List Action'
description: 'Get Image List from Ops-monster'
author: 'jambam <hs.cho@bucketplace.net>'
inputs:
  app_name:
    required: true
    description: 'Application name registered in ops-monster'
  base_url:
    required: true
    description: 'Opsmonster Base Url'
  input_repo:
    required: false
    description: 'Manually input repo'
outputs:
  image_repo:
    description: 'Image repo to register with ECR'
runs:
  using: 'node12'
  main: 'dist/index.js'